spring.h2.console.enabled=false

# Supabase PostgreSQL connection settings.
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.nvvdxzlunhecwoiyexgj
spring.datasource.password=7RCh8Lp%./af@ga
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate updates the database schema from the JPA entity classes on startup.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
